---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
spec:
  selector:
    matchLabels:
      app: backend-pod
  template:
    metadata:
      labels:
        app: backend-pod
    spec:
      containers:
        - name: backend-pod
          # 여러분의 backend image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_bb028510ab49
          resources:
            requests:
              memory: 1Gi
          volumeMounts:
          - name: backend-config
            mountPath: /app/.secret
        volumes:
        - name: backend-config
          configMap:
            name: backend-secret
            
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend-pod
  ports:
    - port: 5000
      targetPort: 5000
