---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendDep
spec:
  selector:
    matchLabels:
      app: frontendPod
  template:
    metadata:
      labels:
        app: frontendPod
    spec:
      containers:
        - name: frontendPod
          # 여러분의 frontend image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_59cb53310758
---
apiVersion: v1
kind: Service
metadata:
  name: frontendSvc
spec:
  selector:
    app: frontendDep
  ports:
    - port: 3000
      targetPort: 3000
