---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
spec:
  selector:
    matchLabels:
      app: frontend-dep
  template:
    metadata:
      labels:
        app: frontend-dep
    spec:
      containers:
        - name: frontend-pod
          # 여러분의 frontend image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_59cb53310758
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend-dep
  ports:
    - port: 3000
      targetPort: 3000
