namespace: default
resources:
  - nginx.yaml
  - frontend.yaml
  - backend.yaml
configMapGenerator:
  - name: nginx
    files:
      - configs/nginx/default.conf
  - name: backend-secret
    files:
      - configs/backend/.secret
